# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel, QWidget
from PyQt5.QtGui import QPixmap, QImage
import sys, cv2
from PyQt5.QtCore import QTimer, QRect, Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 728)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listChat = QtWidgets.QListView(self.centralwidget)
        self.listChat.setGeometry(QtCore.QRect(765, 31, 371, 451))
        self.listChat.setObjectName("listChat")
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(1060, 500, 81, 61))
        self.btnSend.setObjectName("btnSend")
        self.edtNhap = QtWidgets.QTextEdit(self.centralwidget)
        self.edtNhap.setGeometry(QtCore.QRect(770, 500, 281, 61))
        self.edtNhap.setObjectName("edtNhap")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(920, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 55, 16))
        self.label_2.setObjectName("label_2")
        self.btnCamera = QtWidgets.QPushButton(self.centralwidget)
        self.btnCamera.setGeometry(QtCore.QRect(50, 580, 161, 51))
        self.btnCamera.setObjectName("btnCamera")
        self.btnMic = QtWidgets.QPushButton(self.centralwidget)
        self.btnMic.setGeometry(QtCore.QRect(260, 580, 81, 51))
        self.btnMic.setObjectName("btnMic")
        self.btnQuit = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuit.setGeometry(QtCore.QRect(1060, 580, 81, 51))
        self.btnQuit.setObjectName("btnQuit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(39, 39, 711, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.screen1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.screen1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.screen1.setText("")
        self.screen1.setObjectName("screen1")
        self.gridLayout.addWidget(self.screen1, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.startVideo()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSend.setText(_translate("MainWindow", "Send"))
        self.edtNhap.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Box chat"))
        self.label_2.setText(_translate("MainWindow", "Video"))
        self.btnCamera.setText(_translate("MainWindow", "Hide/Show Camera"))
        self.btnMic.setText(_translate("MainWindow", "On/Off Mic"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))

    def startVideo(self):
        self.cap = cv2.VideoCapture(0)
        fps = int(self.cap.get(cv2.CAP_PROP_FPS))
        self.timer = QTimer()
        millisecs = int(1000.0 / fps)
        self.timer.setTimerType(Qt.PreciseTimer)
        self.timer.timeout.connect(self.nextFrameSlot)
        self.timer.start(millisecs)
        

    def nextFrameSlot(self):
        ret, frame = self.cap.read()
        if ret == True:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            img = QImage(frame,frame.shape[1], frame.shape[0], QImage.Format_RGB888)
            pix = QPixmap.fromImage(img)            
            pix = pix.scaled(self.screen1.width(),self.screen1.height(), Qt.KeepAspectRatio, Qt.SmoothTransformation)
            self.screen1.setPixmap(pix) 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
